### ISSUE TITLE
Incorrect Transaction Receipt Status Error Thrown Despite Status.Success in Hedera Wallet Connect Integration

### ISSUE THREAD

**Issue by MiguelLZPF** [hiero-ledger/hiero-sdk-js#2287]
### Description

When integrating Hedera Wallet Connect into the Stablecoin project using version 2.44.0 of the Hashgraph SDK and the programming language, an issue arises where the transaction receipt status is incorrectly reported as an error despite being Status.Success. The error occurs in the TransactionResponse.js file.

We expected the transaction receipt status to be correctly reported as Status.Success after sending a transaction successfully using the Blade wallet. However, the actual behavior is that the status is reported as an error, which is incorrect.

### Steps to reproduce

1. Use version 2.44.0 of the Hashgraph SDK.
2. Setup Stablecoin project (branch feat/hwc-check-new-pr-code).
3. Use the provided branch for hedera-wallet-connect: https://github.com/hashgraph/hedera-wallet-connect/pull/116.
4. Test sending a transaction with Blade wallet using Wallect Connect.
6. Despite the status being Status.Success, an error is thrown.

### Additional context

- The error is thrown from the getReceiptWithSigner function in TransactionResponse.js.
- The issue seems to be related to the handling of the transaction receipt status.
- The error message indicates that the status is SUCCESS, contradicting the error reported.
- The provided branch: https://github.com/hashgraph/hedera-wallet-connect/pull/116 is being used for testing.

`[ERROR]	StatusError: receipt for transaction 0.0.3990677@1715241225.888703971 contained error status SUCCESS
    at new ReceiptStatusError
    at TransactionResponse.getReceiptWithSigner`

### Hedera network

testnet

### Version

v2.44.0

### Operating system

macOS

**Comment by agadzhalov** [comment]
>Setup Stablecoin project (branch feat/hwc-check-new-pr-code).
can you provide a link to the repository?

**Comment by MiguelLZPF** [comment]
> > Setup Stablecoin project (branch feat/hwc-check-new-pr-code).
> 
> can you provide a link to the repository? @MiguelLZPF

Yes, of course. [stablecoin-studio](https://github.com/hashgraph/stablecoin-studio)

**Comment by agadzhalov** [comment]
@MiguelLZPF can you share more information how exactly `stablecoin-studio` interacts with `hedera-wallet-connect` and step by step framework how to reproduce it? 
- From what I understood we should setup the `stablecoin-studio` from branch `feat/hwc-check-new-pr-code`. Is there anything more specific we need from this project, is there specific module we need to use? Does this project include example dapp we have to use? If yes how can we run it?

> Use the provided branch for hedera-wallet-connect: https://github.com/hashgraph/hedera-wallet-connect/pull/116.
- Why should we use this specific branch here? Also how can we setup the `hedera-wallet-connect` to interact with `stablecoin-studio` is there anything missed?
> Test sending a transaction with Blade wallet using Wallect Connect.
- Where should we test this transaction, is there any dApp running? Is the transaction tested through a web app or a console app? If it's a console app can you provide the exact snippet you've used? 
- Can you provide a simple and clean snippet with the transaction that throws the error, so we can test it in independent environment and make sure if the issue is from the JavaScript SDK?

**Comment by MiguelLZPF** [comment]
@agadzhalov, Sorry for my late reply, I missed the notification. I understand it is difficult to reproduce, hope this more detailed steps are more clear:

# Steps

## 1. Clone Stablecoin repository

```bash
  git clone https://github.com/hashgraph/stablecoin-studio
  cd stablecoin-studio
  git checkout feat/hwc-check-new-pr-code
```

## 2. install dependencies and build project

```bash
  npm install
  # wait until finished
```

## 3. Clone test branch with signer methods

```bash
  git clone https://github.com/pwoosam/hedera-wallet-connect.git
  cd hedera-wallet-connect
  git checkout feature/dappsigner
```

## 4. Change Hedera Wallet Connect dependencie (If PR is merged, this step is no longer necessary)

Change the `"@hashgraph/hedera-wallet-connect"` dependencie in the Stablecoin SDK package.json to point to this repository.

Here you have three options:
  1. Use file. `"@hashgraph/hedera-wallet-connect": <route/to/pwoosam/hedera-wallet-connect>`
  2. Use NPM link.
  3. Use local repository like [verdaccio](https://github.com/verdaccio/verdaccio) (this works best for us)

## 5. Test using Stablecoin WEB

### 5.1 Hedera wallet

An hedera wallet with an account is needed. Easyest way is to use Hedera portal and import that account to the Blade Wallet.
**Blade Wallet browser extension and a Chrome based browser are needed for this test**.

### 5.2 Web Environment

You need to have a correct .env configured on the web directory. Example:

```env
# Log level for the application. The default value is ERROR.
# Acceptable values are ERROR, WARN, INFO, HTTP, VERBOSE, DEBUG and SILLY in order of priority (highest to lowest).
REACT_APP_LOG_LEVEL=DEBUG
# JSON array with a factory id in Hedera format `0.0.XXXXX` per environment.
REACT_APP_FACTORIES='[{"Environment":"testnet","STABLE_COIN_FACTORY_ADDRESS":"0.0.2167166"}]'
# The var must be a unique mirror node service for Hedera network, and this is the service which would be used when the UI starts. If the service doesn't require an API key to authorize requests, the API_KEY and HEADER properties must remain empty.
REACT_APP_MIRROR_NODE='[{"Environment":"testnet","BASE_URL":"https://testnet.mirrornode.hedera.com/api/v1/", "API_KEY": "", "HEADER": ""}]'
# The var must be a unique RPC node service for Hedera network, and this is the service which would be used when the UI starts. If the service doesn't require an API key to authorize requests, the API_KEY and HEADER properties must remain empty.
REACT_APP_RPC_NODE='[{"Environment":"testnet","BASE_URL":"https://testnet.hashio.io/api", "API_KEY": "", "HEADER": ""}]'
# This is a proprietary Create React App configuration. You can read more information in its documentation.[Create React App documentation](https://create-react-app.dev/docs/advanced-configuration/)
GENERATE_SOURCEMAP=true
REACT_APP_SHOW_CONFIG=true
```

### 5.3 Test

```bash
  cd stablecoin-studio/web
  npm start
```

#### 5.3.1 Create a test stablecoin

1. Open Stablecoin
2. Connect Blade Wallet **witout using wallet connect**
3. Create new Stablecoin
   1. Click on the + sign
   2. Give it a name and symbol
   3. Leave others to defaults
   4. Accept all

#### 5.3.2 Create example transaction

1. Open inspect tab to see logs
2. Connect Blade **using Hedera Wallet Connect option**
3. Choose the previously created Stablecoin
4. Go to Operations
5. Click on Cash In
6. Enter amount 2, for example
7. Copy and paste same account as the used to connect wallet in Destination account
8. Click on Accept and sign the transaction
9. You will see the error on the logs and on a pop up

If you need clarification on any of them, let me know. 

> * Why should we use this specific branch here? Also how can we setup the `hedera-wallet-connect` to interact with `stablecoin-studio` is there anything missed?
This is needed because the signer.cal() method is not implemented on the main branch at the moment. We need it to get the receipt after Tx execution.

> * Where should we test this transaction, is there any dApp running? Is the transaction tested through a web app or a console app? If it's a console app can you provide the exact snippet you've used?
The stablecoin (web) is the dApp that I hope you can run with the previously provided steps.

> * Can you provide a simple and clean snippet with the transaction that throws the error, so we can test it in independent environment and make sure if the issue is from the JavaScript SDK?
You can see the execution details [here](https://hashscan.io/testnet/transaction/1715241236.505409794) the transaction itself is a mint operation.

**Comment by agadzhalov** [comment]
@MiguelLZPF thank you for the detailed explanation. But as I am currently on `step 2` it's not possible to build the project successfully because an `ECONNREFUSED` is thrown trying to send a request to `localhost`. This only happens when I am on `feat/hwc-check-new-pr-code`. When I checkout `main` and run `npm install` the project is build successfully. I think there's possibility some of the changes in the branch to break the build. Can we confirm this?

> npm ERR! FetchError: request to http://localhost:4873/preact/-/preact-10.4.1.tgz failed, reason: connect ECONNREFUSED ::1:4873
> npm ERR!     at ClientRequest.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
> npm ERR!     at ClientRequest.emit (node:events:513:28)
> npm ERR!     at Socket.socketErrorListener (node:_http_client:502:9)
> npm ERR!     at Socket.emit (node:events:525:35)
> npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
> npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)

**Comment by MiguelLZPF** [comment]
Yeah, seems some package-lock.json that is pointing to a local npm repository. Let me check it and I will come back to you.

**Comment by MiguelLZPF** [comment]
It is strange, but I have clean cloned 2 times the repo, changed to the branch and execute the install process without any issue. I will check with my colleagues to see if they can get the error.

**Comment by MiguelLZPF** [comment]
Yes, you were right, pull changes and try again, should be working now

**Comment by agadzhalov** [comment]
@MiguelLZPF tried again in a clean environment, but the result and the error is the same. Still builds successfully on `main`

**Comment by agadzhalov** [comment]
@MiguelLZPF yes, I've pulled the changes, tested again in new clear environment, also a colleague of mine tried `npm install` with the latest changes from the branch and the same error is thrown again.

**Comment by MiguelLZPF** [comment]
We will test it internally again because today the PR was merged and maybe there are new things to consider. I have updated the steps to test (basically removed the 3 and 4 steps) so should be easy to reproduce the issue when we can fix the step 2 problem. I will let you know when we test it. Thanks!!

**Comment by MiguelLZPF** [comment]
Hi @agadzhalov,

The hedera-wallet-connect version 1.1.1 was published last Friday, y have test it. yesterday and the same error happened. I have updated [the steps to test it](https://github.com/hashgraph/hedera-sdk-js/issues/2287#issuecomment-2124137490), hopefully you can go through them now.

I leave you some screenshots of the error if that helps, thanks again.
<img width="469" alt="image" src="https://github.com/hashgraph/hedera-sdk-js/assets/10762009/1c58f473-aaa3-4963-a32e-9cffd1e688d6">
<img width="688" alt="image" src="https://github.com/hashgraph/hedera-sdk-js/assets/10762009/7b517dbc-2264-4fd4-9fd9-89d4049bd447">

**Comment by agadzhalov** [comment]
> Connect Blade using Hedera Wallet Connect option

@MiguelLZPF after starting the web application I have only two options **Metamask** and **Blade** as you can see in the screenshot. Can you give more details how can I connect Blade using Hedera Wallet Connetc?
![image](https://github.com/hashgraph/hedera-sdk-js/assets/77534278/9b59a86a-0012-4a1f-9a83-397e890d1d06)

**Comment by MiguelLZPF** [comment]
What browser are you using for testing?

**Comment by MiguelLZPF** [comment]
`No hedera-wallet-connect option?`
This was my fault sorry. Add this to the .env of the WEB module.
```
REACT_APP_PROJECT_ID='8fc26370383a50de1c3bd638d334292e'
REACT_APP_DAPP_NAME='StableCoin'
REACT_APP_DAPP_DESCRIPTION='StableCoin is a decentralized stablecoin platform built on Hedera Hashgraph.'
REACT_APP_DAPP_URL='https://wc.hgraph.app/'
REACT_APP_DAPP_ICONS=['https://stablecoinstudio.com/static/media/hedera-hbar-logo.4fd73fb360de0fc15d378e0c3ebe6c80.svg']
```
I have the same error creating a new Stablecoin, I am checking it. But you can see this issue error if you perform the Stablecoin creation connecting using Wallet Connect. **So please check that you are able to connect Blade wallet using Wallet connect and try to create a new Stable Coin**

**Comment by gregscullard** [comment]
Bump :)
Alternatively, @MiguelLZPF could you create a very simple test app to replicate this without having to setup stable coin studio as a whole, it may be quicker ?

**Comment by MiguelLZPF** [comment]
Hi @gregscullard!
Of course, it will be quicker to test 🙂, and we might even discover something else in the process. But it will take time to develop. I will send you details.

**Comment by MiguelLZPF** [comment]
Hello @agadzhalov,

Following @gregscullard 's suggestion, we believe a meeting would help accelerate the testing and replication of this issue. This way, we can demonstrate the issue and the steps leading to it.

Could you please let me know if this works for you and your team? Additionally, please indicate your preferred platform (Zoom, GMeet, Slack, etc.). We are available between 08:00 and 18:00 CEST

**Comment by agadzhalov** [comment]
HI @MiguelLZPF, sorry for the late answers, do you still face this issue? Did you manage to find any workarounds? Are you somehow blocked? Currently we are working on new functionalities and this is the reason for the late answer. If you still face issue we can schedule a meeting for next week Tuesday - Friday (16-19th July between 08:00 and 18:00 EEST).

**Comment by MiguelLZPF** [comment]
@agadzhalov Yes, all is in the same status as last time. I have invited you to a [meeting](https://meet.google.com/hix-wofz-pqv) on Thursday, July 18 · 13:00 – 14:00 CEST (or 14 - 15 in EEST) I hope it is OK for you.

**Comment by agadzhalov** [comment]
@MiguelLZPF  can we reschedule the meeting either for tomorrow Wednesday July 17 13:00 – 14:00 CEST (or 14 - 15 in EEST) or for Friday July 19 13:00 – 14:00 CEST (or 14 - 15 in EEST)?

**Comment by MiguelLZPF** [comment]
@agadzhalov I was just thinking about recording a video with the issue:
https://github.com/user-attachments/assets/c93a4f32-fc47-420b-b1f2-cfe3365e6000
Anyway I moved the meeting to tomorrow.

**Comment by MiguelLZPF** [comment]
Hi guys! Thank you for your efforts in testing this issue; it was indeed a strange one.
After performing more testing, incorporating the latest Stablecoin changes, and removing HashConnect from it, we are pleased to report that this error no longer appears in any of our flows. As a result, we can now close this issue.

**Comment by MiguelLZPF** [comment]
Hello, I am sorry to inform you that we faced this issue again in another project. Same exact issue, this time we have to implement a workaround but it is far from been a good one:
```
    try {
      const receiptPromise = transactionResponse.getReceiptWithSigner(signer);
      const timeoutPromise = new Promise<TransactionReceipt | boolean>(
        (resolve) => {
          setTimeout(() => resolve(false), timeout * 1000);
        },
      );
      return Promise.race([receiptPromise, timeoutPromise]);
    } catch (error: any) {
      if (error.status) {
        if (error.status.toString() === 'SUCCESS') {
          return true;
        }
      }
      throw error;
    }
```

To reproduce the error in this new project you will need to:

1. `git clone https://github.com/hashgraph/asset-tokenization-studio.git` (will be public on 2024-09-17)
2. `cd asset-tokenization-studio/`
3. `checkout success-issue`
3. `npm run install:all`
4. `cd web && npm install -g yarn@1.22.19`
5. `cp .env.sample .env`
6. Create new project in WalletConnect Cloud
7. Copy Project ID to .env **REACT_APP_PROJECT_ID**
8. `yarn dev`
9. Go to localhost:5173
10. Click on "Connect Wallet Connect"
![image](https://github.com/user-attachments/assets/670af516-2c8e-4e48-8959-d330f2a136c1)
11. Connect Blade Wallet (you can use HashPack, but Blade is more stable)
12. Create new digital security
13. New equity
14. Fill required values
15. Create Equity
16. Transaction works, receipt correct but error thrown...

**Comment by ivaylogarnev-limechain** [comment]
Hi @MiguelLZPF,

I've gone through the entire thread and followed your most recent instructions, but I wasn’t able to reproduce the issue because the `fix/success-issue-in-receipt` branch is currently unavailable.

That said, we've introduced quite a few changes to the `Executable` class since the issue first came up, and I’m fairly confident that the false positive behavior should now be resolved.

Could you please update to the latest JS SDK version [v2.63.0](https://github.com/hiero-ledger/hiero-sdk-js/pull/3057), give it a try, and let us know if the issue still persists?

Thanks!

**Comment by MiguelLZPF** [comment]
Hi @ivaylogarnev-limechain,

Thank you for attempting to reproduce the issue. We will try the latest SDK version when possible and will get back to you.

Regards

**Comment by ivaylogarnev-limechain** [comment]
Hey @MiguelLZPF, 

Did you manage to check on this?

**Comment by jaime-iobermudez** [comment]
Hi @ivaylogarnev-limechain, testing with the last version `v2.64.5`, error still appears when calling the`getReceiptWithSigner` method from the `TransactionResponse` class,

Transaction Id: `0.0.4942556@1748271487.426889506`

![Image](https://github.com/user-attachments/assets/573a5093-d7d5-456a-8ae1-d213b198f9f2)

Also, I leave you this branch with the `v2.64.5` if you want to try --> https://github.com/hashgraph/asset-tokenization-studio/tree/fix/hashgraph-sdk-version

**Comment by ivaylogarnev-limechain** [comment]
> Hi [@ivaylogarnev-limechain](https://github.com/ivaylogarnev-limechain), testing with the last version `v2.64.5`, error still appears when calling the`getReceiptWithSigner` method from the `TransactionResponse` class,
> 
> Transaction Id: `0.0.4942556@1748271487.426889506`
> 
> ![Image](https://github.com/user-attachments/assets/573a5093-d7d5-456a-8ae1-d213b198f9f2)
> 
> Also, I leave you this branch with the `v2.64.5` if you want to try --> https://github.com/hashgraph/asset-tokenization-studio/tree/fix/hashgraph-sdk-version

Thank you for the provided details and for sharing the branch. We're currently looking into the issue and will follow up if anything else is needed.

**Comment by jaime-iobermudez** [comment]
Hi @gregscullard , after reviewing the issue with @ivaylogarnev-limechain , it appears to be related to outdated Chrome extensions. Hashpack is using the latest version and experiences no issues, whereas Blade has not updated its app since December, which is where the error is occurring.
 
Are you ok with closing this, since it's just a non-blocking console error that depends on blade?

**Comment by ivaylonikolov7** [comment]
I think I am okay with closing the issue: 

1. We've found that the issue is with Blade and not the SDK itself. We could reproduce the issue only with the Blade wallet.
2. Original creator of the isssue hasn't responded to us in almost 2 months so I think it's safe to say we can close it.

**Comment by gregscullard** [comment]
We can close indeed.
